#!/Users/jonathankirchman/compNeuro/week2/python/quiz2

from __future__ import division
import numpy as np
import matplotlib.pyplot as plt

import pickle

from compute_sta import compute_sta


FILENAME = 'c1p8_3.4.pickle'

with open(FILENAME, 'rb') as f:
    data = pickle.load(f)

stim = data['stim']
rho = data['rho']

sampling_period = 2
num_timesteps = 150

prior = 0
for n in range(0,num_timesteps):
    val = rho[n,0]
    prior = prior + val

num_obv_spikes = sum(rho) - prior

sta = compute_sta(stim, rho, num_timesteps, num_obv_spikes)

time = (np.arange(-num_timesteps, 0) + 1) * sampling_period

plt.plot(time, sta)
plt.xlabel('Time (ms)')
plt.ylabel('Stimulus')
plt.title('Spike-Triggered Average')

plt.show()
